/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank;

import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Andreas E.S
 */
public class Home extends javax.swing.JFrame {

    Registration reg = new Registration();
    Menu menu = new Menu();
    FlowLayout l = new FlowLayout();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Section();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnOK = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ForgetPassword = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-BANK");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(892, 1463));

        MainPanel.setBackground(new java.awt.Color(237, 241, 241));
        MainPanel.setForeground(new java.awt.Color(0, 102, 255));
        MainPanel.setLayout(null);

        Login.setBackground(new java.awt.Color(237, 241, 241));
        Login.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Niagara Solid", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Username");
        Login.add(jLabel2);
        jLabel2.setBounds(34, 91, 44, 22);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Niagara Solid", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Password");
        Login.add(jLabel4);
        jLabel4.setBounds(34, 154, 44, 22);

        txtUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        Login.add(txtUsername);
        txtUsername.setBounds(96, 88, 344, 32);

        pwdPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Login.add(pwdPassword);
        pwdPassword.setBounds(96, 152, 344, 30);

        btnOK.setFont(new java.awt.Font("Niagara Solid", 0, 20)); // NOI18N
        btnOK.setForeground(new java.awt.Color(51, 51, 51));
        btnOK.setText("OK");
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        Login.add(btnOK);
        btnOK.setBounds(96, 213, 98, 38);

        btnReset.setFont(new java.awt.Font("Niagara Solid", 0, 20)); // NOI18N
        btnReset.setForeground(new java.awt.Color(51, 51, 51));
        btnReset.setText("RESET");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        Login.add(btnReset);
        btnReset.setBounds(339, 213, 101, 38);

        jLabel5.setFont(new java.awt.Font("Niagara Solid", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 119, 235));
        jLabel5.setText("New here? Click here to signup");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        Login.add(jLabel5);
        jLabel5.setBounds(26, 269, 222, 17);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Niagara Solid", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("WELCOME TO E-BANK NAMIBIA");
        jLabel1.setInheritsPopupMenu(false);
        Login.add(jLabel1);
        jLabel1.setBounds(140, 22, 238, 31);

        ForgetPassword.setFont(new java.awt.Font("Niagara Solid", 0, 15)); // NOI18N
        ForgetPassword.setForeground(new java.awt.Color(42, 119, 235));
        ForgetPassword.setText("Forgot your password? Click here");
        ForgetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPasswordMouseClicked(evt);
            }
        });
        Login.add(ForgetPassword);
        ForgetPassword.setBounds(386, 269, 117, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\digits\\Documents\\NetBeansProjects\\FisrtActualApp\\src\\Bank\\photo-of-a-laptop-and-a-tablet-on-the-table-2528118.jpg")); // NOI18N
        Login.add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 330);

        MainPanel.add(Login);
        Login.setBounds(427, 168, 530, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\digits\\Documents\\NetBeansProjects\\FisrtActualApp\\src\\Bank\\photo-of-a-laptop-and-a-tablet-on-the-table-2528118.jpg")); // NOI18N
        MainPanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 1370, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String password = new String(this.pwdPassword.getPassword());

        if (txtUsername.getText().isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:sqlserver://localhost:1433; databaseName=Bank; user=sa; password=Nust2019";
                Connection con = (Connection) DriverManager.getConnection(url);
                
                //Authenticating the user
                String ver = "select * from Registration where Username=? and Password = ?";
                PreparedStatement pre = con.prepareStatement(ver);
                
                //geting the username and password from the user and match them with the ones in the database
                pre.setString(1, txtUsername.getText());
                pre.setString(2, password);
                ResultSet re = pre.executeQuery();

                //granting the user access if the field details are matching with the ones in the database
                if (re.next()) {
                    JOptionPane.showMessageDialog(null, "Login successfull!");
                    
                    //switching panels
                    MainPanel.removeAll();
                    MainPanel.revalidate();
                    MainPanel.repaint();
                    
                    MainPanel.add(menu);
                    MainPanel.setLayout(l);
                    MainPanel.revalidate();
                    MainPanel.repaint();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password!");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtUsername.setText(null);
        pwdPassword.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();

        MainPanel.add(reg);
        MainPanel.setLayout(l);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void ForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPasswordMouseClicked
         Password p = new Password();
        
         MainPanel.removeAll();
         MainPanel.revalidate();
         MainPanel.repaint();
         
         MainPanel.add(p);
         MainPanel.setLayout(l);
         MainPanel.revalidate();
         MainPanel.repaint();
    }//GEN-LAST:event_ForgetPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //Main method of the application
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetPassword;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void Section() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("eb.png")));
    }
}
